service: usuarioService

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

plugins:
  - serverless-offline

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: user
          method: post
          cors: true
  readAll:
    handler: handler.readAll
    events:
      - http:
          path: user
          method: get
  readOne:
    handler: handler.readOne
    events:
      - http:
          path: user/{id}
          method: get
          cors: true
  login:
    handler: handler.login
    events:
      - http:
          path: user/login
          method: post
          cors: true
  update:
    handler: handler.update
    events:
      - http:
          path: user/{id}
          method: put
          cors: true
  delete:
    handler: handler.delete
    events:
      - http:
          path: user/{id}
          method: delete
          cors: true