service: reconhecimentoService

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "rekognition:*"
      Resource: "*"
package:
  include:
   - ../node_modules/**

plugins:
  - serverless-offline
   
functions:
  analyseFace:
    handler: handler.analyseFace
    events:
      - http:
          path: analyseFace
          method: post
          cors: true